### ISSUE TITLE
Feature request: call a tool with options

### ISSUE THREAD

**Issue by olleolleolle** [emilebosch/gem-exec#1]
I attempted to call an uninstalled tool with options, was not lucky. Is that possible to change?

`gem exec brakeman -- -o brakeman.html`

(Of course, this would work, soon after:)

`brakeman -o brakeman.html`

**Comment by emilebosch** [comment]
Heya! I can make that, but I sorta abandoned this, because I made something that already exists 😢 , called gemx from the makers of ruby gems

**Comment by olleolleolle** [comment]
Appreciate the link! https://github.com/rubygems/gemx
